name: First Workflow

on: 
 push:
   branches: 
         - main

jobs:
 example-jobs:
    runs-on: ubuntu-latest
    steps:
       - name: Print a Walcome massage 
         run: echo "Welcome the First GitHub Action hi Salah" 

       - name: Print Update
         run: echo "Update"
     
         
