name: Second WorkFlow

on: 
  push:
     branches: 
        - main


jobs:
   example-job:
     runs-on: ubuntu-latest

     steps:
        - name: Print message
          run: echo "Yes the Workflow "
     
